### ISSUE TITLE
todo balancing

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#234]
- [x] remove HE from SPG-9 UAZ
- [x] remove HE from BMP
- [x] check for skins woodland/desert
- [x] ace clacker bla
