### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#237]
- [x] buy menu weirdness (not spawning or double spawning veh)
- [x] spawn inside/under start vehicle instead of next to it
- [x] HAT no mag in barrel
- [x] buy options lost on disco
- [x] CSAT bei disco
- [x] cant lay down satchels?
- [x] grad fortificatons update
- [x] vehicle spawn marker duration
- [x] longer sandbags for defence pack
- [x] remove external retract/deploy actions at radio truck as they interfere with internal
- [x] undefined gamemode
- [x] remove ace fortify
